[project]
name = "mcptrace"
version = "0.1.0"
description = "MCP server for bpftrace kernel tracing"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"